/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#5a001c",
        "outline": "#ab888b",
        "on-primary-fixed-variant": "#910031",
        "surface-container-highest": "#35343a",
        "inverse-primary": "#bd0043",
        "primary": "#ffb2ba",
        "tertiary-container": "#18a659",
        "surface-dim": "#131318",
        "surface": "#131318",
        "surface-container-low": "#1b1b20",
        "on-secondary-container": "#4f3100",
        "outline-variant": "#5b4042",
        "background": "#131318",
        "surface-tint": "#ffb2ba",
        "surface-bright": "#39383e",
        "on-tertiary-fixed": "#00210c",
        "tertiary-fixed-dim": "#61de8a",
        "on-error-container": "#ffdad6",
        "surface-container": "#1f1f25",
        "inverse-on-surface": "#303036",
        "on-tertiary-container": "#003115",
        "surface-variant": "#35343a",
        "secondary": "#ffb955",
        "secondary-fixed-dim": "#ffb955",
        "on-primary-fixed": "#400011",
        "secondary-fixed": "#ffddb4",
        "tertiary": "#61de8a",
        "inverse-surface": "#e4e1e9",
        "tertiary-fixed": "#7efba4",
        "on-surface-variant": "#e3bdc0",
        "on-secondary-fixed": "#291800",
        "on-background": "#e4e1e9",
        "primary-fixed": "#ffd9dc",
        "primary-fixed-dim": "#ffb2ba",
        "on-error": "#690005",
        "secondary-container": "#dc9100",
        "on-secondary-fixed-variant": "#633f00",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#005228",
        "on-secondary": "#452b00",
        "on-primary": "#670021",
        "on-tertiary": "#00391a",
        "on-surface": "#e4e1e9",
        "surface-container-high": "#2a292f",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e13",
        "primary-container": "#ff4f74"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-4xl": "3rem",
        "space-xl": "1.5rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-3xl": "2.5rem",
        "space-2xl": "2rem",
        "margin-desktop": "2rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "space-xxs": "0.125rem",
        "space-base": "1rem",
        "space-md": "0.75rem"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.025em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
export default config;
